<a href="https://colab.research.google.com/github/mcondemaita/python_projects/blob/main/2Dimensional_Np_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
#Create a list 
a = [[11,12,13], [21,22,23], [31,32,33]] #3 nest list 
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [6]:
#we can cast the list to Numpy Array 
#Every elemt is the same type 
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [7]:
#use the attributes  ndim to obtaing the number of axes or dimensons, referred to as the rank 
A.ndim # show dimenstion 

2

In [8]:
#the appribute shape returns a tuple correspomding the size or number of each dimension 
A.shape # land and with on column and rows 
#show the numpy array shape 

(3, 3)

In [15]:
A.size

9

In [14]:
B= np.array([[1,2,1], [0,1,1]])
B.shape

(2, 3)

In [16]:
#to select use the square brackets and the indices corresponding the element  
x =A[0][0]# Access to the 1 element on the 1 row and 1 column 
x

11

In [18]:
y= B[0][1] # Access the 1 row and 2nd column 
y

2

In [20]:
#slice the rows, Access the elements on the 1 & 2 columns 

div = A[0,0:2]
div


array([11, 12])

In [21]:
#Access the 1 & 2 row and 3 column  
last = A[0:2,2] 
last

array([13, 23])

In [22]:
#add metrix by individual colors
x = np.array([[1,0], [0,1]])
y = np.array([[2,1],[1,2]])


array([[3, 1],
       [1, 3]])

In [23]:
#We can add them numpy arrays as follow: 
#Add X & y

z = x+y
z

array([[3, 1],
       [1, 3]])

In [45]:
y = np.array([[2,1],[1,2]])
Z = 2*(y) #this should be [4,2], [2,4]
z

array([[7, 5],
       [5, 7]])

Multiplying a numpy array by a  scaler is identical to multiplying a matrix by scaale. If We multiply matrix Y by scaler 2 
use the dot to go one by one make sure the number of column and rows are igual in this case 3 Exp
Row # 1
A = 0*1 + 1*1 + 1*-1 =0 multi by rows 
A = 0*1 + 1*1 + 1*1 = 2 see below 
Row #2
A = 1*1 + 0*1 + 1*-1 = 0 

In [24]:
Z_ = 2*y #Multiply Y with 2 
Z_

array([[4, 2],
       [2, 4]])

In [25]:
#Multiply X with Y

Final = x*y
Final

array([[2, 0],
       [0, 2]])

In [11]:
#Perform matrix miltiplication with the numpy  array A &B 
A_ = np.array([[0,1,1],[1,0,1]]) #goes one by one
B_ = np.array([[1,1], [1,1], [-1,1]])
A_

array([[0, 1, 1],
       [1, 0, 1]])

In [12]:
B_

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [13]:
#we use the numpy funtions dot to  multiply arrrays together 
c_ = np.dot(A_,B_)
c_

array([[0, 2],
       [0, 2]])

In [14]:
np.sin(c_) # Calculate the  sine of Z

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [15]:
c_.T #T  to calculate the trasposes matrix 

array([[0, 0],
       [2, 2]])

Test 

In [16]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [21]:
df = np.array(a)
df.size

12