<a href="https://colab.research.google.com/github/mcondemaita/python_projects/blob/main/Two_Dimensional_Np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = [[11,12,13], [21,22,23], [31,32,33]] #3 nest list 
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [7]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
A.ndim #dimenstion 

2

In [9]:
A.shape # land and with on column and rows 

(3, 3)

In [10]:
A.size

9

In [15]:
B= np.array([[1,2,1], [0,1,1]])
B.shape

(2, 3)

In [19]:
#to select a value form the list 
x =[[A[0][0]]]
x

[[11]]

In [21]:
y= [[B[0][1]]]
y

[[2]]

In [23]:
#slice the rodes 

div = [A[0,0:2]]
div


[array([11, 12])]

In [25]:
last = [A[0:2,2]]
last

[array([13, 23])]

In [35]:
#add metrix by individual colors
x = np.array([[1,0], [0,1]])
y = np.array([[2,1],[1,2]])
z = x+y
z

array([[3, 1],
       [1, 3]])

In [45]:
y = np.array([[2,1],[1,2]])
Z = 2*(y) #this should be [4,2], [2,4]
z

array([[7, 5],
       [5, 7]])

Metrix multiplitication 
use the dot to go one by one make sure the number of column and rows are igual in this case 3 Exp
Row # 1
A = 0*1 + 1*1 + 1*-1 =0 multi by rows 
A = 0*1 + 1*1 + 1*1 = 2 see below 
Row #2
A = 1*1 + 0*1 + 1*-1 = 0 

In [55]:
A_ = np.array([[0,1,1],[1,0,1]]) #goes one by one
B_ = np.array([[1,1], [1,1], [-1,1]])
c_ = np.dot(A_,B_)
c_

array([[0, 2],
       [0, 2]])